# -*- coding: utf-8 -*-
"""hash_util.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vY0JdirrF_63iUGhljOnFiMvzYFoIm_V
"""

with open("hash_util.py", "w") as f:
    f.write("""
import os
import hashlib
import base64

def hash_password(password, iterations=100_000):
    salt = os.urandom(16)
    dk = hashlib.pbkdf2_hmac('sha256', password.encode(), salt, iterations)
    return salt.hex(), base64.b64encode(dk).decode()
""")